/* Practice 3 */

ALTER TABLE FACT.Checkout
ADD PRIMARY KEY (Check_Num) NOT NULL; 

ALTER TABLE FACT.PATRON
ADD PRIMARY KEY (PAT_ID); 

ALTER TABLE FACT.BOOK
ADD PRIMARY KEY (BOOK_NUM)

ALTER TABLE FACT.AUTHOR
ADD PRIMARY KEY (Au_ID)

ALTER TABLE FACT.Checkout
ADD FOREIGN KEY (Book_Num) REFERENCES FACT.BOOK (Book_Num);

ALTER TABLE FACT.Checkout
ADD FOREIGN KEY (Pat_ID) REFERENCES FACT.PATRON (Pat_ID);

ALTER TABLE FACT.WRITES
ADD PRIMARY KEY (Book_Num, Au_ID)

ALTER TABLE FACT.WRITES
ADD FOREIGN KEY (Book_Num) REFERENCES FACT.BOOK (Book_Num); 

ALTER TABLE FACT.WRITES
ADD FOREIGN KEY (Au_ID) REFERENCES FACT.AUTHOR (Au_ID);

ALTER TABLE FACT.PATRON
ADD CONSTRAINT typecheck CHECK (pat_type IN ('Faculty','Student'));

INSERT INTO FACT.PATRON 
VALUES (1444,'Jake','Owens','Guest')
