/* Practice Problem 3 */ 

CREATE OR ALTER PROCEDURE FACT.sqBookReturn @BOOK_NUM INT AS
DECLARE 
	@BOOKEXISTS INT,
	@CHECKPATRON INT;
BEGIN
	
	SET @BOOKEXISTS = (SELECT COUNT(1) FROM FACT.BOOK WHERE BOOK_NUM = @BOOK_NUM); 
	IF @BOOKEXISTS = 0
		PRINT(CONCAT('No Book ', @BOOK_NUM, ' found.'));  
	ELSE
		BEGIN
			SET @CHECKPATRON = (SELECT PAT_ID FROM FACT.BOOK WHERE BOOK_NUM = @BOOK_NUM);
			IF @CHECKPATRON IS NOT NULL 
				BEGIN
					 UPDATE FACT.BOOK 
					 SET PAT_ID = NULL 
					 WHERE BOOK_NUM = @BOOK_NUM; 
					 UPDATE FACT.CHECKOUT
					 SET CHECK_IN_DATE = GETDATE()
					 WHERE BOOK_NUM = @BOOK_NUM AND CHECK_IN_DATE IS NULL; 
				END;
			ELSE 
				PRINT CONCAT('Book ' , @BOOK_NUM, ' is not currently checked out.'); 
		END; 

END; 

SELECT * FROM FACT.CHECKOUT; 

EXEC sqBookReturn 5249; 