SELECT C.CUST_CODE
	 , CONCAT(CUST_FNAME, ' ', CUST_LNAME) AS CUSTOMER
	 , FORMAT(SUM(LINE_PRICE * LINE_QTY), 'C') AS "Hardware Total"
	 , COUNT(DISTINCT I.INV_NUM) AS "# Of Invoices"
FROM CUSTOMER C JOIN INVOICE I ON C.CUST_CODE = I.CUST_CODE
	JOIN LINE L ON I.INV_NUM = L.INV_NUM
	JOIN PRODUCT P ON L.PROD_NUM = P.PROD_NUM
WHERE PROD_CATEGORY = 'HARDWARE'
GROUP BY 
	C.CUST_CODE
	, CONCAT(CUST_FNAME, ' ', CUST_LNAME)
HAVING 
	COUNT(DISTINCT I.INV_NUM) > 5
ORDER BY 
	C.CUST_CODE, "Hardware Total"; 