-- Correlated Subqueries

-- Evaluates subqueries for each row in a query

-- Evaluate line quantities of products where the line quantity is greater than the average line_quantity for that same product. 
SELECT INV_NUM
	, LINE_NUM
	, PROD_NUM
	, LINE_QTY
	, LINE_PRICE
FROM LINE OUTERLINE
WHERE LINE_QTY > (SELECT AVG(LINE_QTY) FROM LINE INNERLINE WHERE OUTERLINE.PROD_NUM = INNERLINE.PROD_NUM) 
ORDER BY INV_NUM, LINE_NUM; 


SELECT *
FROM EMPLOYEE OUTEMP
WHERE EMP_SALARY > (SELECT AVG(EMP_SALARY) FROM EMPLOYEE INEMP WHERE OUTEMP.EMP_TITLE = INEMP.EMP_TITLE)
ORDER BY EMP_NUM; 



-- Not Correlated
SELECT EMP_NUM
	, EMP_FNAME
	, EMP_LNAME
FROM EMPLOYEE
WHERE EMP_NUM IN (SELECT EMP_MANAGER FROM EMPLOYEE)
ORDER BY EMP_NUM; 


-- If you use a correlated subquery, the EXISTS operator can have value as it shifts between each row. 
SELECT EMP_NUM
	, EMP_FNAME
	, EMP_LNAME
FROM EMPLOYEE E1
WHERE EXISTS( SELECT 1 FROM EMPLOYEE E2 WHERE E1.EMP_NUM = E2.EMP_MANAGER)
ORDER BY EMP_NUM; 


SELECT DISTINCT A.EMP_NUM
	, A.EMP_FNAME
	, A.EMP_LNAME
FROM EMPLOYEE A JOIN EMPLOYEE B ON A.EMP_NUM = B.EMP_MANAGER
ORDER BY A.EMP_NUM; 