-- LOGIC FUNCTIONS

-- COALESCE
-- SHORT HAND FOR A SPECIAL CASE FUNCTION 

SELECT COALESCE(NULL, 'B', 'C'); -- returns first value that is not null

SELECT ISNULL('A', 'IT IS NULL'); -- Displays first value if not null, and second value if null. 


-- Changes null value to 0 in column with lots of nulls
SELECT EMP_NUM
	, EMP_LNAME
	, EMP_TITLE
	, ISNULL(EMP_COMM, 0) AS EMP_COMM
FROM EMPLOYEE
ORDER BY EMP_NUM; 

SELECT AVG(ISNULL(EMP_COMM, 0)) AS AVG_COMM
FROM EMPLOYEE

-- CASE STATEMENT

-- SIMPLE

SELECT CUST_CODE
	, CUST_STATE
	, CASE CUST_STATE
	  WHEN 'TX' THEN 'TEXAS'
	  WHEN 'NY' THEN 'New York'
	  WHEN 'CA' THEN 'CALIFORNIA'
	  ELSE 'OTHER'
	  END STATE
FROM CUSTOMER
ORDER BY CUST_CODE; 

-- SEARCHED CASE 

SELECT CUST_CODE
	, CUST_STATE
	, CUST_BALANCE
	, CASE 
	  WHEN CUST_BALANCE > 400 AND CUST_STATE = 'AL' THEN 'BIG BAMA BALANCE'
	  WHEN CUST_BALANCE < 400 AND CUST_STATE = 'AL' THEN 'SMALL BAMA BALANCE' 
	  WHEN CUST_STATE IN ('AL','GA','MS','TN') THEN 'SOUTHERN'
	  ELSE 'OTHER'
	  END 'SWEET HOME'
FROM CUSTOMER
ORDER BY CUST_CODE; 

-- IIF Function (Immediate IF)

SELECT P.PROD_NUM, INV_NUM, LINE_NUM, LINE_QTY, LINE_PRICE, PROD_PRICE, 
	IIF(LINE_PRICE < PROD_PRICE, (PROD_PRICE - LINE_PRICE) * LINE_QTY, 0) AS "Savings"
FROM PRODUCT P JOIN LINE L ON P.PROD_NUM = L.PROD_NUM
WHERE LINE_QTY > 5
ORDER BY INV_NUM, LINE_NUM;

-- CHOOSE FUNCTION

SELECT EMP_NUM, EMP_HIREDATE, CHOOSE(MONTH(EMP_HIREDATE), 'WINTER','WINTER','SPRING','SPRING','SPRING','SUMMER','SUMMER','SUMMER','FALL','FALL','FALL','WINTER') AS SEASON
FROM EMPLOYEE
ORDER BY EMP_NUM; 

-- ISNULL() VS IS NULL

SELECT * 
FROM EMPLOYEE
WHERE EMP_COMM IS NULL;  -- CORRECT
