SELECT C.CUST_CODE
	   , CONCAT(CUST_FNAME, ' ', CUST_LNAME) AS "Customer Name"
	   , INV_NUM
	   , INV_DATE
	   , FORMAT(INV_TOTAL,'C') AS "Sale Total"
	   , EMP_NUM
	   , CONCAT(EMP_LNAME, ', ', EMP_FNAME) AS Employee 
	   , CONCAT(EMP_Comm * 100, '%') AS "Commission Rate"
	   , FORMAT(INV_TOTAL * EMP_Comm, 'C') AS "Sale Commission"
FROM CUSTOMER C  
	JOIN INVOICE I ON C.CUST_CODE = I.CUST_CODE
	JOIN EMPLOYEE E ON E.EMP_NUM = I.EMPLOYEE_ID
WHERE INV_DATE BETWEEN '2022-01-01' AND '2022-01-31'
	AND INV_TOTAL > 500
	AND CUST_STATE IN ('AL','TN')
ORDER BY EMP_LNAME, INV_DATE; 